# global default
container:
  image: ruby:latest

# test_task:
#   container:
#     matrix:
#       - image: default-debian-9-2019-2-py3
#       - image: default-ubuntu-1804-2019-2-py3
#       # - image: default-centos-7-2019-2-py3
#       # - image: default-fedora-29-2019-2-py3
#       # - image: default-opensuse-leap-15-2019-2-py3
#       # - image: default-debian-9-2018-3-py2
#       # - image: default-ubuntu-1604-2018-3-py2
#       # - image: default-centos-7-2018-3-py2
#       # - image: default-fedora-29-2018-3-py2
#       # # TODO: Use this when fixed instead of `opensuse-leap-42`
#       # # Ref: https://github.com/netmanagers/salt-image-builder/issues/2
#       # # - image: default-opensuse-leap-15-2018-3-py2
#       # - image: default-opensuse-leap-42-2018-3-py2
#       # - image: default-debian-8-2017-7-py2
#       # - image: default-ubuntu-1604-2017-7-py2
#       # # TODO: Enable after improving the formula to work with other than `systemd`
#       # - image: default-centos-6-2017-7-py2
#       # - image: default-fedora-28-2017-7-py2
#       # - image: default-opensuse-leap-42-2017-7-py2
#   # env:
#   #   matrix:
#   #     - COMMAND: test
#   #     # - COMMAND: lint
#   test_script:
#     - gem install bundler
#     - bundle install
#     - bundle exec kitchen verify ${image}

test_task:
  # container:
  #   image: netmanagers/salt-2019.2-py3:debian-9
  install_bundler_script: gem install bundler
  bundle_cache:
    folder: /usr/local/bundle
    # fingerprint_script: cat Gemfile.lock
    populate_script: bundle install
  test_script: bundle exec kitchen verify default-debian-9-2019-2-py3

# test_task:
#   container:
#     image: default-ubuntu-1804-2019-2-py3
#   bundle_cache:
#     folder: /usr/local/bundle
#     fingerprint_script: cat Gemfile.lock
#     populate_script: bundle install
#   test_script: bundle exec kitchen verify default-ubuntu-1804-2019-2-py3
